# Generated by Django 2.1.5 on 2020-04-10 19:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0002_auto_20200410_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_corta', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0))),
                ('descripcion_larga', models.TextField(blank=True, default='')),
                ('etiqueta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='documentos.Etiqueta')),
            ],
        ),
    ]
