# Generated by Django 2.1.5 on 2020-04-11 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_etiqueta_hito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='hito',
            old_name='descripcion_larga',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='hito',
            old_name='descripcion_corta',
            new_name='tema',
        ),
        migrations.RenameField(
            model_name='hito',
            old_name='etiqueta',
            new_name='tipo_de_publicacion',
        ),
        migrations.AddField(
            model_name='hito',
            name='emisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='documentos.Emisor'),
        ),
    ]
