# Generated by Django 2.1.5 on 2020-04-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_auto_20200411_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentosOficiales',
            new_name='DocumentoOficial',
        ),
    ]
